---
all:
  children:
    networking:
      hosts:
        reverse-proxy:
          ansible_host: 192.168.1.101

    k8s-cluster:
      hosts:
        k8s-master:
          ansible_host: 192.168.1.201
        k8s-worker-1:
          ansible_host: 192.168.1.211

    gaming:
      hosts:
        minecraft-server:
          ansible_host: 192.168.1.51
