---
- name: Gitlab Bootstrap Configuration
  include_tasks: bootstrap.yml
  tags: k8s-gitlab

- name: Gitlab Configuration
  include_tasks: gitlab.yml
  tags: k8s-gitlab

- name: Gitlab Service Configuration
  include_tasks: service.yml
  tags: k8s-gitlab

- name: Gitlab Runner Configuration
  include_tasks: runner.yml
  tags: k8s-runner
