---
- name: Gitlab Service Configuration
  become: false
  delegate_to: localhost
  block:
    - name: Deploy GitLab Service
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: v1
          kind: Service
          metadata:
            name: gitlab-service
            namespace: gitlab
          spec:
            selector:
              app: gitlab
            ports:
              - name: http
                port: 80
                targetPort: 80
              - name: ssh
                port: 22
                targetPort: 22

    - name: Deploy Middleware for GitLab
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: traefik.io/v1alpha1
          kind: Middleware
          metadata:
            name: secure-headers
            namespace: gitlab # Đẻ Middleware ngay trong xóm gitlab
          spec:
            headers:
              sslRedirect: true
              forceSTSHeader: true
              stsIncludeSubdomains: true
              stsPreload: true
              stsSeconds: 31536000
              customFrameOptionsValue: "SAMEORIGIN"
              contentTypeNosniff: true
              browserXssFilter: true
              referrerPolicy: "strict-origin-when-cross-origin"

    - name: Deploy Traefik IngressRoute for GitLab
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: traefik.io/v1alpha1
          kind: IngressRoute
          metadata:
            name: gitlab-ingress
            namespace: gitlab
          spec:
            entryPoints:
              - web
            routes:
              - match: Host(`gitlab.{{ base_domain }}`)
                kind: Rule
                services:
                  - name: gitlab-service
                    port: 80
                middlewares:
                  - name: secure-headers
