- name: Format disk
  community.general.filesystem:
    fstype: ext4
    dev: "/dev/{{ backup_disk_device }}"

- name: Get disk UUID
  command: "blkid -s UUID -o value /dev/{{ backup_disk_device }}"
  register: hdd_uuid
  changed_when: false

- name: Unsure mount directory existed
  file:
    path: "{{ backup_dir }}"
    state: directory
    mode: "0755"

- name: Mount HDD and auto write to /etc/fstab by UUID get already
  mount:
    path: "{{ backup_dir }}"
    src: "UUID={{ hdd_uuid.stdout }}"
    fstype: ext4
    opts: defaults,nofail
    state: mounted
