- name: Deploy Traefik IngressRoute for GitLab
  kubernetes.core.k8s:
    state: present
    definition: |
      apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: prmoxox-ingress
        namespace: gitlab
      spec:
        entryPoints:
          - web
        routes:
          - match: Host(`proxmox.{{ base_domain }}`)
            kind: Rule
            services:
              - name: gitlab-service
                port: 80
            middlewares:
              - name: secure-headers
