---
base_domain: nooblearn2code.com
gitlab_version: "16.11.0-ce.0"

cloudflare_ddns_version: "latest"
cloudflare_ddns_image: "oznu/cloudflare-ddns:{{ cloudflare_ddns_version }}"
cloudflare_ddns_container: cloudflare-ddns
cloudflare_ddns_zone: "{{ base_domain }}"
cloudflare_ddns_subdomain: "gateway"

# Gitlab
gitlab_config_mount_path: "{{ ssd_mount_path }}/gitlab/config"
gitlab_data_mount_path: "{{ ssd_mount_path }}/gitlab/data"

# Seafile
seafile_mount_path: "{{ hdd_mount_path }}/seafile"

# Persistent Volumes
persistent_volumes: # <name>-pv
  - {
      name: "gitlab-config",
      storage: "2Gi",
      policy: "Retain",
      class: "local-path",
      type: "local",
      path: "{{ gitlab_config_mount_path }}",
      node: "k8s-worker-1",
    }
  - {
      name: "seafile",
      storage: "100Gi",
      policy: "Retain",
      class: "local-path",
      type: "local",
      path: "{{ seafile_mount_path }}",
      node: "k8s-worker-1",
    }
