---
# ========== POSTGRES ========== #
postgres_root_user: "noob"
postgres_root_password: "nooblearn2code_postgres_pass"
postgres_port: 5432
postgres_node: k8s-worker-1

# Databases
postgres_databases:
  - { name: "gitlab", user: "gitlab", password: "gitlab_db_pass" }
  - { name: "esl", user: "esl", password: "esl_db_pass" }
  - {
      name: "auth-service",
      user: "auth",
      password: "nooblearn2code_database_password",
    }
  - {
      name: "blog-service",
      user: "blog",
      password: "nooblearn2code_database_password",
    }
  - {
      name: "uniquizz-service",
      user: "uniquizz",
      password: "nooblearn2code_database_password",
    }
  - { name: "resumind-service", user: "resumind", password: "hoanggxyuuki" }
  - { name: "lunar-service", user: "lunar", password: "hoanggxyuuki" }
  - { name: "seafile", user: "seafile", password: "seafile_db_pass" }

# ========== REDIS ========== #
redis_password: "nooblearn2code_redis_pass"
redis_port: 6379
