---
- name: Restart Traefik
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_config_dir }}"
    state: restarted

- name: Restart Cloudflare Tunnel
  community.docker.docker_compose_v2:
    project_src: "{{ cloudflare_tunnel_config_dir }}"
    state: restarted