---
- hosts: all
  become: true
  roles:
    - role: bootstrap
      tags: bootstrap

- hosts: reverse-proxy
  become: true

  roles:
    - role: docker
      tags: docker

    - role: proxy
      tags: proxy

- hosts: minecraft-server
  become: true

  roles:
    - role: docker
      tags: docker

    - role: backup
      tags: backup

    - role: minecraft
      tags: minecraft
