---
- name: Create Cloudflare DDNS configuration directory
  file:
    path: "{{ cloudflare_ddns_config_dir }}"
    state: directory
    mode: "0755"

- name: Create Cloudflare DDNS compose.yml file
  template:
    src: templates/cf-ddns/compose.yml.j2
    dest: "{{ cloudflare_ddns_config_dir }}/compose.yml"
    mode: "0644"

- name: Start Cloudflare DDNS using Docker Compose
  command: docker compose up -d
  args:
    chdir: "{{ cloudflare_ddns_config_dir }}"
  register: compose_output
  changed_when: "'Started' in compose_output.stdout or 'Created' in compose_output.stdout"
