---
- name: Create Cloudflare Tunnel configuration directory
  file:
    path: "{{ cloudflare_tunnel_config_dir }}"
    state: directory
    mode: "0755"
  tags: tunnel

- name: Create Cloudflare Tunnel compose.yml file
  template:
    src: cf-tunnel/compose.yml.j2
    dest: "{{ cloudflare_tunnel_config_dir }}/compose.yml"
    mode: "0644"
  tags: tunnel

- name: Copy Cloudflare Tunnel credentials file
  ansible.builtin.copy:
    src: tunnel-credentials.json
    dest: "{{ cloudflare_tunnel_config_dir }}/credentials.json"
    mode: '0644'
  tags: tunnel
  notify: Restart Cloudflare Tunnel

- name: Render config.yml file for Cloudflare Tunnel
  ansible.builtin.template:
    src: cf-tunnel/config.yml.j2
    dest: "{{ cloudflare_tunnel_config_dir }}/config.yml"
    mode: '0644'
  tags: tunnel
  notify: Restart Cloudflare Tunnel

- name: Ensure Cloudflare Tunnel is running
  community.docker.docker_compose_v2:
    project_src: "{{ cloudflare_tunnel_config_dir }}"
    state: present
  tags: tunnel