---
- name: Đảm bảo service Docker đang chạy
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create shared Docker Network
  community.docker.docker_network:
    name: "{{ edge_network }}"
    driver: bridge
    state: present

- name: Cloudflare DDNS Configuration
  include_tasks: cf-ddns.yml
  when: cloudflare_ddns_enabled

- name: Cloudflare Tunnel Configuration
  include_tasks: cf-tunnel.yml
  when: cloudflare_tunnel_enabled
  tags: tunnel

- name: Traefik Configuration
  include_tasks: traefik.yml
  tags: traefik
